const citiesToDrinksMap = {
  'Pago Pago, American Samoa': 'Mai Tai',
  'Midway Atoll, United States': 'Rum Punch',
  'Honolulu, United States': 'Blue Hawaii',
  'Papeete, French Polynesia': 'Maitai Roa Ae',
  'Rarotonga, Cook Islands': 'Pina Colada',
  'Anchorage, United States': 'Alaskan Amber',
  'Los Angeles, United States': 'Margarita',
  'Vancouver, Canada': 'Caesar',
  'Tijuana, Mexico': 'Tequila Sunrise',
  'Denver, United States': 'Colorado Bulldog',
  'Calgary, Canada': 'Caesar',
  'Phoenix, United States': 'Desert Martini',
  'Mexico City, Mexico': 'Paloma',
  'Chicago, United States': 'Old Fashioned',
  'Tegucigalpa, Honduras': 'Pinolillo',
  'New York, United States': 'Manhattan',
  'Toronto, Canada': 'Maple Whiskey Sour',
  'Bogotá, Colombia': 'Aguardiente',
  'Lima, Peru': 'Pisco Sour',
  'Caracas, Venezuela': 'Cuba Libre',
  'La Paz, Bolivia': 'Singani Sour',
  'Santo Domingo, Dominican Republic': 'Mamajuana',
  "St. John's, Canada": 'Screech Rum',
  'Buenos Aires, Argentina': 'Fernet and Cola',
  'São Paulo, Brazil': 'Caipirinha',
  'Montevideo, Uruguay': 'Medio y Medio',
  'Ponta Delgada, Portugal': 'Ginjinha',
  'London, United Kingdom': 'Gin and Tonic',
  'Reykjavik, Iceland': 'Brennivín',
  'Accra, Ghana': 'Akpeteshie',
  'Dublin, Ireland': 'Irish Coffee',
  'Berlin, Germany': 'Jägermeister',
  'Paris, France': 'French 75',
  'Rome, Italy': 'Negroni',
  'Lagos, Nigeria': 'Palm Wine',
  'Cairo, Egypt': 'Sakara Beer',
  'Johannesburg, South Africa': 'Amarula',
  'Athens, Greece': 'Ouzo',
  'Kyiv, Ukraine': 'Horilka',
  'Moscow, Russia': 'Vodka',
  'Riyadh, Saudi Arabia': 'Non-Alcoholic Cocktail',
  'Nairobi, Kenya': 'Dawa',
  'Baghdad, Iraq': 'Arak',
  'Tehran, Iran': 'Non-Alcoholic Beer',
  'Dubai, United Arab Emirates': 'Non-Alcoholic Mojito',
  'Baku, Azerbaijan': 'Narsharab',
  'Samara, Russia': 'Kvass',
  'Tbilisi, Georgia': 'Chacha',
  'Kabul, Afghanistan': 'Non-Alcoholic Cocktail',
  'Islamabad, Pakistan': 'Non-Alcoholic Margarita',
  'Yekaterinburg, Russia': 'Medovukha',
  'Karachi, Pakistan': 'Non-Alcoholic Beer',
  'Tashkent, Uzbekistan': 'Vodka',
  'New Delhi, India': 'Old Monk Rum',
  'Colombo, Sri Lanka': 'Arrack',
  'Mumbai, India': 'Kingfisher Beer',
  'Bengaluru, India': 'Beer',
  'Kathmandu, Nepal': 'Raksi',
  'Dhaka, Bangladesh': 'Non-Alcoholic Beer',
  'Thimphu, Bhutan': 'Ara',
  'Almaty, Kazakhstan': 'Kumis',
  'Naypyidaw, Myanmar': 'Non-Alcoholic Cocktail',
  'Cocos Islands, Australia': 'Beer',
  'Bangkok, Thailand': 'Thai Sabai',
  'Jakarta, Indonesia': 'Non-Alcoholic Beer',
  'Ho Chi Minh City, Vietnam': 'Bia Hoi',
  'Phnom Penh, Cambodia': 'Palm Wine',
  'Beijing, China': 'Baijiu',
  'Singapore, Singapore': 'Singapore Sling',
  'Perth, Australia': 'Emu Export',
  'Kuala Lumpur, Malaysia': 'Non-Alcoholic Cocktail',
  'Tokyo, Japan': 'Sake',
  'Seoul, South Korea': 'Soju',
  'Pyongyang, North Korea': 'Soju',
  'Yakutsk, Russia': 'Vodka',
  'Adelaide, Australia': 'Shiraz',
  'Darwin, Australia': 'Darwin Stubby',
  'Sydney, Australia': 'Fosters',
  'Vladivostok, Russia': 'Vodka',
  'Port Moresby, Papua New Guinea': 'SP Lager',
  'Brisbane, Australia': 'XXXX Beer',
  'Honiara, Solomon Islands': 'SolBrew',
  'Nouméa, New Caledonia': 'Ti Punch',
  'Magadan, Russia': 'Vodka',
  'Wellington, New Zealand': 'Sauvignon Blanc',
  'Suva, Fiji': 'Kava',
  'Nauru, Nauru': 'Non-Alcoholic Beer',
  "Nuku'alofa, Tonga": 'Kava',
  'Apia, Samoa': 'Vailima Beer',
  'Kiritimati, Kiribati': 'Non-Alcoholic Beer',
  Antarctica: 'Mulled Wine',
  'Etc/UTC': 'Cocktail of Choice',
}

export default citiesToDrinksMap
