const timezoneCityData = {
  'Pacific/Midway': {
    cities: ['Pago Pago, American Samoa', 'Midway Atoll, United States'],
    utc_offset: '-11:00',
    abbreviation: 'SST',
    region: 'Pacific',
  },
  'Pacific/Honolulu': {
    cities: ['Honolulu, United States', 'Papeete, French Polynesia', 'Rarotonga, Cook Islands'],
    utc_offset: '-10:00',
    abbreviation: 'HST',
    region: 'Pacific',
  },
  'America/Anchorage': {
    cities: ['Anchorage, United States'],
    utc_offset: '-09:00',
    abbreviation: 'AKST',
    region: 'North America',
  },
  'America/Los_Angeles': {
    cities: ['Los Angeles, United States', 'Vancouver, Canada', 'Tijuana, Mexico'],
    utc_offset: '-08:00',
    abbreviation: 'PST',
    region: 'North America',
  },
  'America/Denver': {
    cities: ['Denver, United States', 'Calgary, Canada', 'Phoenix, United States'],
    utc_offset: '-07:00',
    abbreviation: 'MST',
    region: 'North America',
  },
  'America/Mexico_City': {
    cities: ['Mexico City, Mexico', 'Chicago, United States', 'Tegucigalpa, Honduras'],
    utc_offset: '-06:00',
    abbreviation: 'CST',
    region: 'Central America',
  },
  'America/New_York': {
    cities: ['New York, United States', 'Toronto, Canada', 'Bogotá, Colombia', 'Lima, Peru'],
    utc_offset: '-05:00',
    abbreviation: 'EST',
    region: 'North America',
  },
  'America/Caracas': {
    cities: ['Caracas, Venezuela', 'La Paz, Bolivia', 'Santo Domingo, Dominican Republic'],
    utc_offset: '-04:00',
    abbreviation: 'VET',
    region: 'South America',
  },
  'America/St_Johns': {
    cities: ["St. John's, Canada"],
    utc_offset: '-03:30',
    abbreviation: 'NST',
    region: 'North America',
  },
  'America/Argentina/Buenos_Aires': {
    cities: ['Buenos Aires, Argentina', 'São Paulo, Brazil', 'Montevideo, Uruguay'],
    utc_offset: '-03:00',
    abbreviation: 'ART',
    region: 'South America',
  },
  'Atlantic/Azores': {
    cities: ['Ponta Delgada, Portugal'],
    utc_offset: '-01:00',
    abbreviation: 'AZOT',
    region: 'Atlantic',
  },
  'Europe/London': {
    cities: ['London, United Kingdom', 'Reykjavik, Iceland', 'Accra, Ghana', 'Dublin, Ireland'],
    utc_offset: '+00:00',
    abbreviation: 'GMT',
    region: 'Europe',
  },
  'Europe/Berlin': {
    cities: ['Berlin, Germany', 'Paris, France', 'Rome, Italy', 'Lagos, Nigeria'],
    utc_offset: '+01:00',
    abbreviation: 'CET',
    region: 'Europe',
  },
  'Africa/Johannesburg': {
    cities: ['Cairo, Egypt', 'Johannesburg, South Africa', 'Athens, Greece', 'Kyiv, Ukraine'],
    utc_offset: '+02:00',
    abbreviation: 'SAST',
    region: 'Africa',
  },
  'Europe/Moscow': {
    cities: ['Moscow, Russia', 'Riyadh, Saudi Arabia', 'Nairobi, Kenya', 'Baghdad, Iraq'],
    utc_offset: '+03:00',
    abbreviation: 'MSK',
    region: 'Europe',
  },
  'Asia/Tehran': {
    cities: ['Tehran, Iran'],
    utc_offset: '+03:30',
    abbreviation: 'IRST',
    region: 'Asia',
  },
  'Asia/Dubai': {
    cities: ['Dubai, United Arab Emirates', 'Baku, Azerbaijan', 'Samara, Russia', 'Tbilisi, Georgia'],
    utc_offset: '+04:00',
    abbreviation: 'GST',
    region: 'Asia',
  },
  'Asia/Kabul': {
    cities: ['Kabul, Afghanistan'],
    utc_offset: '+04:30',
    abbreviation: 'AFT',
    region: 'Asia',
  },
  'Asia/Karachi': {
    cities: ['Islamabad, Pakistan', 'Yekaterinburg, Russia', 'Karachi, Pakistan', 'Tashkent, Uzbekistan'],
    utc_offset: '+05:00',
    abbreviation: 'PKT',
    region: 'Asia',
  },
  'Asia/Kolkata': {
    cities: ['New Delhi, India', 'Colombo, Sri Lanka', 'Mumbai, India', 'Bengaluru, India'],
    utc_offset: '+05:30',
    abbreviation: 'IST',
    region: 'Asia',
  },
  'Asia/Kathmandu': {
    cities: ['Kathmandu, Nepal'],
    utc_offset: '+05:45',
    abbreviation: 'NPT',
    region: 'Asia',
  },
  'Asia/Dhaka': {
    cities: ['Dhaka, Bangladesh', 'Thimphu, Bhutan', 'Almaty, Kazakhstan'],
    utc_offset: '+06:00',
    abbreviation: 'BST',
    region: 'Asia',
  },
  'Asia/Rangoon': {
    cities: ['Naypyidaw, Myanmar', 'Cocos Islands, Australia'],
    utc_offset: '+06:30',
    abbreviation: 'MMT',
    region: 'Asia',
  },
  'Asia/Bangkok': {
    cities: ['Bangkok, Thailand', 'Jakarta, Indonesia', 'Ho Chi Minh City, Vietnam', 'Phnom Penh, Cambodia'],
    utc_offset: '+07:00',
    abbreviation: 'ICT',
    region: 'Asia',
  },
  'Asia/Shanghai': {
    cities: ['Beijing, China', 'Singapore, Singapore', 'Perth, Australia', 'Kuala Lumpur, Malaysia'],
    utc_offset: '+08:00',
    abbreviation: 'CST',
    region: 'Asia',
  },
  'Asia/Tokyo': {
    cities: ['Tokyo, Japan', 'Seoul, South Korea', 'Pyongyang, North Korea', 'Yakutsk, Russia'],
    utc_offset: '+09:00',
    abbreviation: 'JST',
    region: 'Asia',
  },
  'Australia/Adelaide': {
    cities: ['Adelaide, Australia', 'Darwin, Australia'],
    utc_offset: '+09:30',
    abbreviation: 'ACST',
    region: 'Australia',
  },
  'Australia/Sydney': {
    cities: ['Sydney, Australia', 'Vladivostok, Russia', 'Port Moresby, Papua New Guinea', 'Brisbane, Australia'],
    utc_offset: '+10:00',
    abbreviation: 'AEST',
    region: 'Australia',
  },
  'Pacific/Guadalcanal': {
    cities: ['Honiara, Solomon Islands', 'Nouméa, New Caledonia', 'Magadan, Russia'],
    utc_offset: '+11:00',
    abbreviation: 'SBT',
    region: 'Pacific',
  },
  'Pacific/Auckland': {
    cities: ['Wellington, New Zealand', 'Suva, Fiji', 'Nauru, Nauru'],
    utc_offset: '+12:00',
    abbreviation: 'NZST',
    region: 'Pacific',
  },
  'Pacific/Tongatapu': {
    cities: ["Nuku'alofa, Tonga", 'Apia, Samoa'],
    utc_offset: '+13:00',
    abbreviation: 'TOT',
    region: 'Pacific',
  },
  'Pacific/Kiritimati': {
    cities: ['Kiritimati, Kiribati'],
    utc_offset: '+14:00',
    abbreviation: 'LINT',
    region: 'Pacific',
  },
  'Antarctica/Casey': {
    cities: [],
    utc_offset: '+08:00',
    abbreviation: 'AWST',
    region: 'Antarctica',
  },
  'Antarctica/Mawson': {
    cities: [],
    utc_offset: '+05:00',
    abbreviation: 'MAWT',
    region: 'Antarctica',
  },
  'Antarctica/Davis': {
    cities: [],
    utc_offset: '+07:00',
    abbreviation: 'DAVT',
    region: 'Antarctica',
  },
  'Antarctica/Vostok': {
    cities: [],
    utc_offset: '+06:00',
    abbreviation: 'VOST',
    region: 'Antarctica',
  },
  'Antarctica/DumontDUrville': {
    cities: [],
    utc_offset: '+10:00',
    abbreviation: 'DDUT',
    region: 'Antarctica',
  },
  'Etc/UTC': {
    cities: [],
    utc_offset: '+00:00',
    abbreviation: 'UTC',
    region: 'Global',
  },
}

export default timezoneCityData
